// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the extension VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace GPTCodeAssistance {
    internal sealed partial class Vsix {
        public const string Id = "GPTCodeAssistance.79992677-dac6-4fd5-a7b3-0dda9427f5d5";
        public const string Name = "GPTCodeAssistance";
        public const string Description = @"Empty VSIX Project.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Company";
        public const string Tags = "";
    }
}
