// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the free extension VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
using System;

namespace GPTCodeAssistance {
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids {
        public const string GPTCodeAssistanceString = "6a404163-c460-4fba-8b10-3d4717fa1a8e";
        public static Guid GPTCodeAssistance = new Guid(GPTCodeAssistanceString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds {
        public const int MyCommand = 0x0100;
    }
}