// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the free extension VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
using System;

namespace GPTCodeAssistance {
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids {
        public const string GPTCodeAssistanceString = "5333bd60-2364-47f8-a200-6e9bc127e52f";
        public static Guid GPTCodeAssistance = new Guid(GPTCodeAssistanceString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds {
        public const int MyCommand = 0x0100;
    }
}