// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the extension VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace GPTCodeAssistant {
    internal sealed partial class Vsix {
        public const string Id = "GPTCodeAssistant.eed0e012-1c8a-474a-a61d-9bbcce625be6";
        public const string Name = "GPTCodeAssistant";
        public const string Description = @"Empty VSIX Project.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Johan Holtby";
        public const string Tags = "";
    }
}
