// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the free extension VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
using System;

namespace GPTCodeAssistant {
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids {
        public const string GPTCodeAssistantString = "f91ee451-dc05-4ee9-9866-2d1f2af2da3f";
        public static Guid GPTCodeAssistant = new Guid(GPTCodeAssistantString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds {
        public const int MyCommand = 0x0100;
    }
}